# Values definition
# Attributes used in the pods

replicas: 1

serviceComponent: transactionservice

image:
  # repository: fabiomatcomp/assignment-2
  repository: transactionservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: transactionservice
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

ingress:
  fqdn: test.transaction.service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"

resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1200Mi

# Actuator health checks, readiness and liveness pointing to the same
# For demo the golang application is always healthy
readinessPath: /api/health
livenessPath: /api/health

# Liveness probe tuning - time in seconds
livenessPeriod: 20
livenessTimeout: 10

# Readiness probe tuning - time in seconds
readinessPeriod: 10
readinessTimeout: 5

db: mysql
dbReplicas: 1
storageSize: "5Gi"

securityContext:
  runAsUser: 11111
  fsGroup: 11111
  supplementalGroups: [ 0 ]

dbImage:
  repository: mysql
  tag: latest
  pullPolicy: IfNotPresent

dbResources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1200Mi