apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionservice
spec:
  selector:
    matchLabels:
      app: transactionservice
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        app: transactionservice
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
{{/*        - name: dummy-to-test*/}}
{{/*          image: busybox*/}}
{{/*          command: ["bin/sh", "-c", 'while true; do sleep 5; done' ]*/}}
        - name: {{ template "transactionservice.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: db-passwd
          resources:
  {{ toYaml .Values.resources | indent 10 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessPath }}
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: {{ .Values.readinessTimeout }}
            periodSeconds: {{ .Values.readinessPeriod }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessPath }}
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: {{ .Values.livenessTimeout }}
            periodSeconds: {{ .Values.livenessPeriod }}